# Generated by Django 3.0 on 2024-01-03 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_basecontent_content_file_image_orderedcontent_text_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderedContent',
        ),
    ]
